Introduce subcommands for main binary, add scanner functionality
avast/k8s-admission-webhook pull request #18
Opened 2019-06-14 11:59 UTC by Flektoma

- main binary now allows only two commands: webhook, scanner
- "webhook" command starts validation webhook same way as before
- "scanner" allows to do one-time outside of cluster scan for objects that are violating validation rules

2019-06-18 15:32 UTC, gorge511 requested changes
I found just few typos, but it looks good to me.
@mighq @petr-k Do you have any other comments?

2019-06-19 08:14 UTC, Flektoma commented on webhook.go
> +	Long: "Starts admission validation webhook verifying incoming objects based on rules spcified by flags",
Fixed

2019-06-19 08:15 UTC, Flektoma commented on README.md
> +Note that every option can also be specified via an environment variable: environment variables should upper-case, using `_` instead of `-` as seen in the flag name. E.g.: `--rule-resource-limit-cpu-
Fixed. All forms of "upper case", "upper-case" and "uppercase" should be fine, however "uppercase" is the most used form.

2019-06-19 08:15 UTC, Flektoma commented on scanner.go
> +	Short:"Scans cluster (from current context) for objects vialoting rules",
Fixed

2019-06-19 08:28 UTC, gorge511 approved these changes
Looks good to me.

2019-06-24 10:11 UTC, merged